FROM alpine:3.15

RUN apk update

RUN apk add openjdk8-jre

RUN apk add tzdata

ENV TZ Asia/Seoul

COPY ./keystore.p12 .

COPY ./build/libs/license-4.0.303.1.jar license.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/license.jar"]
