FROM alpine:3.15

RUN apk update

RUN apk add openjdk8-jre

RUN apk add tzdata

ENV TZ Asia/Seoul

CMD ulimit -c unlimited

COPY ./build/libs/discovery-4.0.303.1.jar discovery.jar

EXPOSE 8761

ENTRYPOINT ["java", "-jar", "/discovery.jar"]
